name: Increment

on:
  workflow_call:
    inputs:
      commit_message:
        required: true
        type: string

jobs:
  increment:
    runs-on: ubuntu-latest
    steps:
    - name: Determine increment
      env:
        commit_message: ${{ github.event.inputs.commit_message }}
      run: |
        echo "Head commit is \"${{ env.commit_message }}\""
        INCREMENT="minor"
        if [ ${{ startsWith(env.commit_message, 'fix:') }} == true ] \
        || [ ${{ startsWith(env.commit_message, 'patch:') }} == true ]; then
          echo "Creating a patch release..."
          INCREMENT="patch"
        elif [ ${{ startsWith(env.commit_message, 'feat:') }} == true ] \
        || [ ${{ startsWith(env.commit_message, 'feat(') }} == true ]; then
          echo "Creating a minor release..."
          INCREMENT="minor"
        elif [ ${{ startsWith(env.commit_message, 'BREAKING CHANGE:') }} == true ]; then
          echo "Creating a major release..."
          INCREMENT="major"
        elif [ ${{ startsWith(env.commit_message, '[skip release]') }} == true ]; then
          echo "Skipping semver increment..."
          INCREMENT="iteration"
        else
          echo "No commit message flag found, using default increment ($INCREMENT)"
        fi
        echo "::set-output name=increment::$(echo "$INCREMENT")"
