name: Increment

on: workflow_call

jobs:
  increment:
    runs-on: ubuntu-latest
    env:
      head_commit: ${{ github.event.head_commit.message }}

    steps:
    - name: Determine increment
      run: |
        echo "Head commit is \"${{ env.head_commit }}\""
        INCREMENT="minor"
        if [ ${{ startsWith(env.head_commit, 'fix:') }} == true ] \
        || [ ${{ startsWith(env.head_commit, 'patch:') }} == true ]; then
          echo "Creating a patch release..."
          INCREMENT="patch"
        elif [ ${{ startsWith(env.head_commit, 'feat:') }} == true ] \
        || [ ${{ startsWith(env.head_commit, 'feat(') }} == true ]; then
          echo "Creating a minor release..."
          INCREMENT="minor"
        elif [ ${{ startsWith(env.head_commit, 'BREAKING CHANGE:') }} == true ]; then
          echo "Creating a major release..."
          INCREMENT="major"
        elif [ ${{ startsWith(env.head_commit, '[skip release]') }} == true ]; then
          echo "Skipping semver increment..."
          INCREMENT="iteration"
        else
          echo "No commit message flag found, using default increment ($INCREMENT)"
        fi
        echo "::set-output name=increment::$(echo "$INCREMENT")"
