SEED = None
DEBUG = True
TOP_FLOOR = 5
MAX_LOOPS = 0
MAX_ROOM_FAILS = 3
FLOOR_SIZE = (27, 27)

FPS = 60
TILE_SIZE = 32
WINDOW_WIDTH = 256
WINDOW_HEIGHT = 224
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)
SCALE_INIT = 2
SCALE_MAX = 6

MOVE_DURATION = 16
ATTACK_DURATION = 12
