name: Release (prod)

on:
  push:
    branches:
      prod

jobs:
  version:
    uses: ./.github/workflows/version.yml
    with:
      default_increment: 'minor'

  build:
    uses: ./.github/workflows/release.yml
    needs: version
    if: ${{ needs.version.outputs.version != '' }}
    with:
      version: ${{ needs.version.outputs.version }}
      prerelease: false
