name: Sandbox

on: pull_request

env:
  PYTHON_VERSION: '3.x'

jobs:
  version:
    uses: ./.github/workflows/version.yml
    with:
      python_version: ${{ env.PYTHON_VERSION }}

  release:
    uses: ./.github/workflows/release.yml
    needs: version
    with:
      version: ${{ needs.version.outputs.version }}
      python_version: ${{ env.PYTHON_VERSION }}
      prerelease: true
