name: Sandbox

on: pull_request

jobs:
  increment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Determine increment
      id: determine_increment
      uses: ./.github/workflows/increment.yml

  print:
    runs-on: windows-latest
    needs: increment
    steps:
    - name: Retrieve increment
      run: |
        echo ${{ needs.increment.steps.determine_increment.outputs.increment }}
