name: Sandbox

on: pull_request

jobs:
  increment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Determine increment
      id: determine_increment
      uses: ./.github/workflows/increment
      with:
        commit_message: ${{ github.event.head_commit.message }}
    - name: Retrieve increment from same job
      run: |
        echo ${{ steps.determine_increment.outputs.increment }}

  print:
    runs-on: ubuntu-latest
    needs: increment
    steps:
    - name: Retrieve increment
      run: |
        echo ${{ toJSON(needs.increment) }}
        echo ${{ needs.increment.outputs.increment }}
