name: Sandbox

on: pull_request

jobs:
  version-increment:
    runs-on: ubuntu-latest
    outputs:
      increment: ${{ steps.determine_increment.outputs.increment }}

    steps:
      - uses: actions/checkout@v3

      - name: Determine increment
        id: determine_increment
        uses: ./.github/workflows/increment
        with:
          commit_message: ${{ github.event.head_commit.message }}

  version-bump:
    runs-on: ubuntu-latest
    needs: version-increment
    if: ${{ needs.version-increment.outputs.increment != 'skip' }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Bump version
        shell: bash
        run: |
          NEW_VERSION=$(python3 bin/bump_version.py ${{ needs.version-increment.outputs.increment }})
          echo "Using new version $NEW_VERSION"
          echo "::set-output name=new_version::$(echo "$NEW_VERSION")"

  # print:
  #   runs-on: windows-latest
  #   needs: increment
  #   steps:
  #   - name: Retrieve increment
  #     run: |
  #       echo "${{ needs.increment.outputs.increment }}"
